library(devtools)
library(ggplot2)

load_all()

set.seed(1)
g1 = graph(lower = 0, upper = 100)
g1 = addNodes(g1, n = 25, generator = addNodesUniform)
g1 = addWeights(g1, generator = addWeightsDistance, method = "euclidean")
g1 = addWeights(g1, generator = addWeightsRandom, method = rnorm, mean = 10, sd = 4.5)
print(g1)
do.call(gridExtra::grid.arrange, plot(g1))

set.seed(1)
g2 = graph(lower = 0, upper = 100)
g2 = addNodes(g2, n = 10, generator = addNodesLHS)
g2 = addNodes(g2, n = 29, by.centers = TRUE, generator = addNodesUniform, lower = c(0, 0), upper = c(5, 5))
g2 = addEdges(g2, type = "intracluster", generator = addEdgesGilbert, p = 0.2)
g2 = addEdges(g2, type = "intracluster", generator = addEdgesSpanningTree)
g2 = addEdges(g2, type = "intercluster", generator = addEdgesDelauney)
g2 = addWeights(g2, generator = addWeightsCorrelated, rho = -0.7)
print(g2)
do.call(gridExtra::grid.arrange, plot(g2))

pls = c(plot(g1), plot(g2), list(ncol = 2L))
pl = do.call(gridExtra::grid.arrange, pls)
ggsave("images/README_graphs.png", plot = pl, width = 15, height = 10)

set.seed(1)
g3 = graph(lower = 0, upper = 100)
g3 = addNodes(g3, n = 100, generator = addNodesGrid)
g3 = addEdges(g3, generator = addEdgesGrid)
g3 = addWeights(g3, generator = addWeightsConcave, M = 100)
do.call(gridExtra::grid.arrange, plot(g3))

set.seed(1)
g4 = graph(lower = 0, upper = 100)
g4 = addNodes(g4, n = 3, generator = addNodesLHS)
g4 = addNodes(g4, n = c(10, 50, 100), by.centers = TRUE, generator = addNodesUniform, lower = c(0, 0), upper = c(15, 15))
g4 = addEdges(g4, type = "intracluster", generator = addEdgesWaxman, alpha = 0.1, beta = 0.3)
g4 = addEdges(g4, type = "intracluster", generator = addEdgesSpanningTree)
g4 = addEdges(g4, type = "intercluster", generator = addEdgesSpanningTree, runs = 2L)
g4 = addWeights(g4, generator = addWeightsDistance, method = "euclidean")
g4 = addWeights(g4, generator = addWeightsRandom, method = rpois, lambda = 10)
do.call(gridExtra::grid.arrange, plot(g4))

pls = c(plot(g1), plot(g2), plot(g3), plot(g4), list(ncol = 4L))
pl = do.call(gridExtra::grid.arrange, pls)
ggsave("paper/examples.pdf", plot = pl, width = 20, height = 11, dpi = 300)
